# Generated by Django 6.1.1 on 2026-09-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=512)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("rack_id", models.PositiveIntegerField(blank=True, null=True)),
                ("retail_price", models.DecimalField(decimal_places=6, max_digits=10)),
                ("latitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("longitude", models.FloatField(blank=True, db_index=True, null=True)),
            ],
            options={
                "ordering": ["opis_id"],
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="fuel_fuelst_latitud_e7de73_idx",
                    ),
                    models.Index(fields=["state", "city"], name="fuel_fuelst_state_99cf3a_idx"),
                ],
            },
        ),
    ]
