# Generated by Django 6.1.1 on 2026-09-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelstation",
            name="geocode_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuelstation",
            name="location_accuracy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exact", "Exact"),
                    ("approximate", "Approximate"),
                    ("city", "City centroid"),
                ],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="fuelstation",
            index=models.Index(
                fields=["location_accuracy", "state"],
                name="fuel_fuelst_locatio_65c583_idx",
            ),
        ),
    ]
